from langchain_openai import OpenAI
from dotenv import load_dotenv
# to import the env variable in this file

load_dotenv()  # Load environment variables from .env file

llm = OpenAI(model_name="gpt-3.5-turbo-instruct", temperature=0.7) #created the object of the class OpenAI and passed the model name and temperature as parameters. The temperature parameter controls the randomness of the output generated by the model. A higher temperature value (e.g., 0.7) will result in more diverse and creative responses, while a lower value (e.g., 0.2) will produce more focused and deterministic outputs.

result = llm.invoke("Write a poem about the beauty of nature.") #invoking the llm object and passing the prompt as a parameter. The invoke method sends the prompt to the OpenAI API and returns the generated response.

print(result)